- name: launch specific number of multiple instances
      amazon.aws.ec2_instance:
        name: "{{ ec2_name }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        count: "{{ count }}"
        region: "{{ region }}"
        instance_role: "{{ IAM_role }}"
        network:
          assign_public_ip: yes
          security_group: "{{ security_group }}"
          vpc_subnet_id: "{{ subnet_id }}"
        state: present
        tags:
          name: 
        user_data: "{{ lookup('file', 'user_data.sh') }}"
